version: "3.9"
services:
  app:
    build: .
    image: vacation-calculator
    container_name: vacation-calculator
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080